on: [push]

jobs:
  example_job:
    runs-on: ubuntu-latest
    name: test the action
    steps:
      - name: test
        uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_api_key: ${{ secrets.ALGOLIA_API_KEY }}
          algolia_application_id: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          file: "config.example.json"
    